#ifndef __HARBOUR_DUCKDB_H
#define __HARBOUR_DUCKDB_H

#include "hbapi.h"
#include "hbapiitm.h"
#include "hbapierr.h"
#include "hbvm.h"
#include "hbstack.h"
#include "hbdate.h"
#include "duckdb.h"

/* 資料庫操作 */
HB_FUNC( DUCKDB_OPEN );
HB_FUNC( DUCKDB_OPEN_EXT );
HB_FUNC( DUCKDB_CLOSE );

/* 連線操作 */
HB_FUNC( DUCKDB_CONNECT );
HB_FUNC( DUCKDB_DISCONNECT );
HB_FUNC( DUCKDB_INTERRUPT );
HB_FUNC( DUCKDB_QUERY_PROGRESS );

/* 查詢操作 */
HB_FUNC( DUCKDB_QUERY );
HB_FUNC( DUCKDB_PREPARE );
HB_FUNC( DUCKDB_EXECUTE );
HB_FUNC( DUCKDB_EXECUTE_STREAMING );
HB_FUNC( DUCKDB_FREE );

/* 結果集操作 */
HB_FUNC( DUCKDB_COLUMN_COUNT );
HB_FUNC( DUCKDB_ROW_COUNT );
HB_FUNC( DUCKDB_ROWS_CHANGED );
HB_FUNC( DUCKDB_COLUMN_NAME );
HB_FUNC( DUCKDB_COLUMN_TYPE );
HB_FUNC( DUCKDB_COLUMN_DATA );
HB_FUNC( DUCKDB_NULLMASK_DATA );

/* 資料類型操作 */
HB_FUNC( DUCKDB_VALUE_BOOLEAN );
HB_FUNC( DUCKDB_VALUE_INT8 );
HB_FUNC( DUCKDB_VALUE_INT16 );
HB_FUNC( DUCKDB_VALUE_INT32 );
HB_FUNC( DUCKDB_VALUE_INT64 );
HB_FUNC( DUCKDB_VALUE_FLOAT );
HB_FUNC( DUCKDB_VALUE_DOUBLE );
HB_FUNC( DUCKDB_VALUE_VARCHAR );
HB_FUNC( DUCKDB_VALUE_BLOB );
HB_FUNC( DUCKDB_VALUE_DATE );
HB_FUNC( DUCKDB_VALUE_TIME );
HB_FUNC( DUCKDB_VALUE_TIMESTAMP );
HB_FUNC( DUCKDB_VALUE_INTERVAL );
HB_FUNC( DUCKDB_VALUE_IS_NULL );

/* 參數綁定 */
HB_FUNC( DUCKDB_BIND_BOOLEAN );
HB_FUNC( DUCKDB_BIND_INT8 );
HB_FUNC( DUCKDB_BIND_INT16 );
HB_FUNC( DUCKDB_BIND_INT32 );
HB_FUNC( DUCKDB_BIND_INT64 );
HB_FUNC( DUCKDB_BIND_FLOAT );
HB_FUNC( DUCKDB_BIND_DOUBLE );
HB_FUNC( DUCKDB_BIND_VARCHAR );
HB_FUNC( DUCKDB_BIND_BLOB );
HB_FUNC( DUCKDB_BIND_DATE );
HB_FUNC( DUCKDB_BIND_TIME );
HB_FUNC( DUCKDB_BIND_TIMESTAMP );
HB_FUNC( DUCKDB_BIND_INTERVAL );
HB_FUNC( DUCKDB_BIND_NULL );

/* 錯誤處理 */
HB_FUNC( DUCKDB_ERROR );
HB_FUNC( DUCKDB_PREPARE_ERROR );

/* 資料類型轉換 */
HB_FUNC( DUCKDB_FROM_DATE );
HB_FUNC( DUCKDB_TO_DATE );
HB_FUNC( DUCKDB_FROM_TIME );
HB_FUNC( DUCKDB_TO_TIME );
HB_FUNC( DUCKDB_FROM_TIMESTAMP );
HB_FUNC( DUCKDB_TO_TIMESTAMP );

#endif /* __HARBOUR_DUCKDB_H */ 